version: '3'
services:
  database:
    image: 'bitnami/redis:latest'
    container_name: 'database'
    environment:
      ALLOW_EMPTY_PASSWORD : 'yes'
    ports:
      - '6379:6379'
    restart: always
